remote_theme: thelehhman/texture
theme: texture
$ gem install texture

texture:
  title: 才子轩
  tagline: student. green hand
  data_format: "%b %-d, %Y"

  social_limks:
    github: sfcaiz-czx
  
  style: [black]